name: CI

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  # Check which files / paths have changed.
  # We use this to inform whether we should run later jobs.
  changes:
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      move_module: ${{ steps.filter.outputs.move_module }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: '.github/filters.yml'
    - name: Print changes
      run: printf "Frontend changed $FRONTEND\nMove module changed $MOVE_MODULE\n"
      env:
        FRONTEND: ${{ steps.filter.outputs.frontend }}
        MOVE_MODULE: ${{ steps.filter.outputs.move_module }}


  # Run the move module tests.
  test_move_module:
    needs: [changes]
    if: needs.changes.outputs.move_module == 'true'
    defaults:
      run:
        working-directory: ./move
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: wget https://github.com/aptos-labs/aptos-core/releases/download/aptos-cli-v0.3.3/aptos-cli-0.3.3-Ubuntu-x86_64.zip -O cli.zip
    - run: unzip cli.zip
    - run: ./aptos move test


  # Publish the move module.
  publish_move_module:
    needs: [test_move_module]
    if: needs.tests.outputs.move_module == 'true'
    defaults:
      run:
        working-directory: ./move
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: wget https://github.com/aptos-labs/aptos-core/releases/download/aptos-cli-v0.3.3/aptos-cli-0.3.3-Ubuntu-x86_64.zip -O cli.zip
    - run: unzip cli.zip
    - run: yes "" | ./aptos init --assume-yes --private-key ${{ secrets.APTOS_ACCOUNT_PRIVATE_KEY }}
    - run: ./aptos move publish


  # Build web and upload the artifact.
  build_web:
    runs-on: ubuntu-latest
    needs: [changes]
    if: needs.changes.outputs.frontend == 'true'
    concurrency: ci-${{ github.ref }}
    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.10.5'
        channel: stable

    # Switch to the web build.
    - run: cd frontend && ./switch_web.sh web

    # Test and build
    - run: cd frontend && flutter pub get
    - run: cd frontend && flutter test
    - run: cd frontend && flutter build web

    # Upload the artifact.
    - uses: actions/upload-pages-artifact@v1
      with:
        path: frontend/build/web


  # Deploy web to GitHub pages using the artifact from the previous job.
  deploy_web:
    runs-on: ubuntu-latest
    needs: [build_web]
    concurrency: ci-${{ github.ref }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/configure-pages@v1
    - id: deployment
      uses: actions/deploy-pages@v1


  # Build, test, sign, publish Android build.
  build_android:
    needs: [changes]
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3

    - run: echo "${{ secrets.UPLOAD_KEYSTORE }}" | base64 -d > android/upload_keystore.jks
    - run: echo "${{ secrets.KEY_PROPERTIES }}" | base64 -d > android/key.properties

    - run: sudo apt update
    - run: sudo apt upgrade -y
    - run: sudo apt install curl wget clang cmake ninja-build libgtk-3-dev pkg-config libssl-dev build-essential

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

    - uses: nttld/setup-ndk@v1
      id: setupndk
      with:
        ndk-version: r24
        add-to-path: false

    - run: native/fix_ndk_gcc.sh
      env:
        ANDROID_NDK_HOME: ${{ steps.setupndk.outputs.ndk-path }}

    - run: cargo install cargo-ndk

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.5'
        channel: stable

    - run: flutter pub get

    - run: flutter test
    # This will produce a signed appbundle.
    - run: flutter build appbundle
      env:
        ANDROID_NDK_HOME: ${{ steps.setupndk.outputs.ndk-path }}

    # Publish release
    - name: Publish Android build to internal track
      uses: r0adkll/upload-google-play@v1.0.15
      with:
        serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
        packageName: com.banool.aclip
        releaseFile: frontend/build/app/outputs/bundle/release/app-release.aab
        track: internal
